/*******************************************************************************
 * SPDX-License-Identifier: MPL-2.0
 *
 * Copyright (c) 2026 Karlsruhe Institute of Technology (KIT)
 * KASTEL - Dependability of Software-intensive Systems
 *
 * This Source Code Form is subject to the terms of the Mozilla
 * Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *******************************************************************************/
package edu.kit.dopler.solvers.shared;

import edu.kit.dopler.model.decisions.IDecision;
import java.util.Objects;

/**
 * Represents an anomaly associated with a specific decision.
 * <p>
 * <b>Equality and Comparison Logic:</b><br>
 * Numeric values generated by ILP/SMT/CP solvers may have different scales or types
 * (e.g., a {@code double} 0.99999999999, a {@code long} 1, or an {@code int} 1000).
 * Because these numeric values cannot be compared directly, any two
 * {@link Number} instances are treated as equal if they belong to the same decision.
 * Non-numeric values use the standard object equality.
 *
 * @param decision The decision associated with this anomaly.
 * @param value    The anomalous value (BooleanLiteral, Number, String, Boolean, etc.).
 */
public record ValueAnomaly(IDecision<?> decision, Object value) implements Comparable<ValueAnomaly> {

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ValueAnomaly(IDecision<?> otherDecision, Object otherValue))) return false;

        if (!Objects.equals(this.decision, otherDecision)) {
            return false;
        }
        if (this.value instanceof Number && otherValue instanceof Number) {
            return true;
        }
        return Objects.equals(this.value, otherValue);
    }

    @Override
    public int hashCode() {
        // To maintain the hashCode contract, equal objects must have the same hash code.
        Object normalizedValue = (this.value instanceof Number) ? 0 : this.value;
        return Objects.hash(this.decision, normalizedValue);
    }

    @Override
    public int compareTo(ValueAnomaly other) {
        int decisionCompare =
                this.decision().getDisplayId().compareTo(other.decision().getDisplayId());
        if (decisionCompare != 0) {
            return decisionCompare;
        }
        // To maintain the compareTo contract, equal objects must have the same hash code.
        if (this.value instanceof Number && other.value instanceof Number) {
            return 0;
        }
        return String.valueOf(this.value()).compareTo(String.valueOf(other.value()));
    }

    @Override
    public String toString() {
        return decision.getDisplayId() + " -> " + value;
    }
}
